import React from 'react'
import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { Brain, Clock, Target, Zap, BookOpen, Award, Users, TrendingUp } from 'lucide-react'

export default function Landing() {
  const features = [
    {
      icon: Brain,
      title: 'AI-Powered Learning',
      description: 'Personalized learning plans generated by advanced AI to match your pace and style'
    },
    {
      icon: Clock,
      title: 'Flexible Scheduling',
      description: 'Learn at your own pace with customizable daily time commitments'
    },
    {
      icon: Target,
      title: 'Goal-Oriented',
      description: 'Set clear learning objectives and track your progress every step of the way'
    },
    {
      icon: Zap,
      title: 'Interactive Quizzes',
      description: 'Test your knowledge with AI-generated quizzes and get instant feedback'
    },
    {
      icon: BookOpen,
      title: 'Comprehensive Content',
      description: 'Deep-dive explanations with real-world examples and practical applications'
    },
    {
      icon: Award,
      title: 'Progress Tracking',
      description: 'Monitor your learning journey with detailed analytics and achievements'
    }
  ]

  const stats = [
    { number: '10K+', label: 'Active Learners' },
    { number: '500+', label: 'Topics Available' },
    { number: '95%', label: 'Completion Rate' },
    { number: '4.9/5', label: 'User Rating' }
  ]

  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="relative overflow-hidden bg-gradient-to-br from-dark-900 via-dark-800 to-primary-900 py-12 sm:py-16 lg:py-20">
        <div className="absolute inset-0 bg-[url('data:image/svg+xml,%3Csvg width=%2260%22 height=%2260%22 viewBox=%220 0 60 60%22 xmlns=%22http://www.w3.org/2000/svg%22%3E%3Cg fill=%22none%22 fill-rule=%22evenodd%22%3E%3Cg fill=%22%23ffffff%22 fill-opacity=%220.02%22%3E%3Ccircle cx=%2230%22 cy=%2230%22 r=%222%22/%3E%3C/g%3E%3C/g%3E%3C/svg%3E')] opacity-20"></div>
        
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
            >
              <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-7xl font-bold mb-4 sm:mb-6">
                Learn Anything with
                <span className="block gradient-text">AI-Powered Precision</span>
              </h1>
              
              <p className="text-lg sm:text-xl md:text-2xl text-dark-300 mb-6 sm:mb-8 max-w-3xl mx-auto px-4">
                Transform your learning journey with personalized AI tutoring, adaptive quizzes, 
                and structured learning plans tailored to your goals and schedule.
              </p>

              <div className="flex flex-col sm:flex-row gap-4 justify-center items-center px-4">
                <Link
                  to="/register"
                  className="btn-primary text-base sm:text-lg px-6 sm:px-8 py-3 sm:py-4 rounded-xl w-full sm:w-auto text-center"
                >
                  Start Learning Today
                </Link>
                <Link
                  to="/login"
                  className="btn-secondary text-base sm:text-lg px-6 sm:px-8 py-3 sm:py-4 rounded-xl w-full sm:w-auto text-center"
                >
                  Sign In
                </Link>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-12 sm:py-16 bg-dark-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-8">
            {stats.map((stat, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                className="text-center"
              >
                <div className="text-2xl sm:text-3xl md:text-4xl font-bold text-primary-400 mb-1 sm:mb-2">
                  {stat.number}
                </div>
                <div className="text-sm sm:text-base text-dark-400">{stat.label}</div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-12 sm:py-16 lg:py-20 bg-dark-900">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12 sm:mb-16">
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold mb-4">
              Why Choose <span className="gradient-text">NeuraLearn</span>?
            </h2>
            <p className="text-lg sm:text-xl text-dark-300 max-w-2xl mx-auto px-4">
              Experience the future of education with our cutting-edge AI technology
              and personalized learning approach.
            </p>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6 sm:gap-8">
            {features.map((feature, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                className="card hover:border-primary-500 transition-colors duration-300"
              >
                <feature.icon className="w-10 h-10 sm:w-12 sm:h-12 text-primary-500 mb-3 sm:mb-4" />
                <h3 className="text-lg sm:text-xl font-semibold mb-2 sm:mb-3">{feature.title}</h3>
                <p className="text-sm sm:text-base text-dark-400">{feature.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="py-12 sm:py-16 lg:py-20 bg-dark-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12 sm:mb-16">
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold mb-4">
              How It <span className="gradient-text">Works</span>
            </h2>
            <p className="text-lg sm:text-xl text-dark-300">
              Get started in just a few simple steps
            </p>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-8 sm:gap-12">
            {[
              {
                step: '01',
                title: 'Choose Your Topic',
                description: 'Tell us what you want to learn and your current skill level'
              },
              {
                step: '02',
                title: 'Get Your Plan',
                description: 'Our AI creates a personalized learning plan just for you'
              },
              {
                step: '03',
                title: 'Start Learning',
                description: 'Follow daily lessons, take quizzes, and track your progress'
              }
            ].map((item, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.2 }}
                className="text-center"
              >
                <div className="w-12 h-12 sm:w-16 sm:h-16 bg-primary-600 rounded-full flex items-center justify-center text-lg sm:text-2xl font-bold mx-auto mb-3 sm:mb-4">
                  {item.step}
                </div>
                <h3 className="text-lg sm:text-xl font-semibold mb-2 sm:mb-3">{item.title}</h3>
                <p className="text-sm sm:text-base text-dark-400">{item.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-12 sm:py-16 lg:py-20 bg-gradient-to-r from-primary-600 to-primary-800">
        <div className="max-w-4xl mx-auto text-center px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
          >
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold text-white mb-4 sm:mb-6">
              Ready to Transform Your Learning?
            </h2>
            <p className="text-lg sm:text-xl text-primary-100 mb-6 sm:mb-8">
              Join thousands of learners who are already achieving their goals with NeuraLearn
            </p>
            <Link
              to="/register"
              className="inline-block bg-white text-primary-600 font-semibold px-6 sm:px-8 py-3 sm:py-4 rounded-xl text-base sm:text-lg hover:bg-primary-50 transition-colors duration-200"
            >
              Get Started for Free
            </Link>
          </motion.div>
        </div>
      </section>
    </div>
  )
}